FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD authorization-server.jar /opt/authorization-server/
EXPOSE 8080
WORKDIR /opt/authorization-server/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "authorization-server.jar"]
