server:
  port: 8080
  servlet:
    context-path: /example
  shutdown: graceful
#  compression:
#    enabled: true
#    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
#  http2:
#    enabled: true

spring:
  application:
    name: spring-boot-grpc
  profiles:
    active: @env@
    include:
      - h2

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    com.github.mbmll: DEBUG
