spring:
  profiles:
    active: dev
#    active: @env@
  application:
    name: project
  mvc:
    throw-exception-if-no-handler-found: false
  #  datasource:
  #    driver-class-name: org.postgresql.Driver
  #    name: defaultDataSource
  #    hikari:
  #      maximum-pool-size: 5
  #      minimum-idle: 1
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
logging:
  level:
    root: error
    org.springframework.web: trace
    org.github.mbmll.snippet: trace
  config:
    classpath: logback-spring.xml

server:
  port: 80
  compression:
    enabled: true
    mime-types: application/json,text/javascript,text/css,text/html,image/jpeg,image/png,application/font-woff

swagger:
  enable: true
  application-name: carbon-user-api
  application-version: 1.0
  application-description: carbon-user-api
