version: '3'

services:
  orcl-1:
    #    image: truevoly/oracle-12c
    build:
      dockerfile: Dockerfile-initdb
    restart: always
    container_name: orcl12c-1
    hostname: orcl-1
    privileged: false
    volumes:
      - ./data_temp/:/home/oracle/data_temp
    ports:
      - 1521:1521
    #      - 8080:8080
    # 查找 Oracle 镜像版本
    #    docker search oracle

    # 下载相对应镜像，这里我们下载 truevoly/oracle-12c 版本
    #    docker pull truevoly/oracle-12c

    # 运行 Docker 容器
    #    docker run -d -p 1521:1521 --name oracle12c truevoly/oracle-12c

    # 进入容器
#    docker exec -it oracle12c /bin/bash