version: '3'

services:
  jobmanager:
    image: flink
    container_name: jobmanager
    command:
      - jobmanager
    environment:
      - TZ=Asia/Shanghai
      - ENABLE_BUILT_IN_PLUGINS=flink-s3-fs-hadoop-1.16.0.jar
    restart: always
    volumes:
#      - /etc/localtime:/etc/localtime:ro
      - ./jobmanager/conf/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
      - ./jobmanager/log:/opt/flink/log:rw
      - ./jobmanager/usrlib:/opt/flink/lib/usrlib:rw
      - ./jobmanager/plugins:/opt/flink/plugins:rw
      - ./jobmanager/user-upload-temp:/opt/flink/user-upload-temp:rw
    ports:
      - 8081:8081
      - 6123:6123
      - 6122:6122
    privileged: true
  taskmanager:
    image: flink
    container_name: taskmanager
    command:
      - taskmanager
    environment:
      - TZ=Asia/Shanghai
      - ENABLE_BUILT_IN_PLUGINS=flink-s3-fs-hadoop-1.16.0.jar
    restart: always
    volumes:
      #      - /etc/localtime:/etc/localtime:ro
      - ./taskmanager/conf/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
      - ./taskmanager/log:/opt/flink/log:rw
      - ./taskmanager/usrlib:/opt/flink/lib/usrlib:rw
      - ./taskmanager/plugins:/opt/flink/plugins:rw
      - ./taskmanager/user-upload-temp:/opt/flink/user-upload-temp:rw
    ports:
      - 6124:6124
      - 6125:6125
      - 6126:6126
    privileged: true

#    user: root

# docker-compose up -d