server:
  port: 8080

spring:
  application:
    name: admin-server
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000 # authorization-server's port
    client:
      registration:
        message
  could:
    nacos:
      discovery:
        server-addr: localhost:8848